### ISSUE TITLE
Using the kernel

### ISSUE THREAD

**Issue by tm4dev** [hexdump0815/linux-mainline-and-mali-allwinner-h3-h6-kernel#1]
hi, thx for your work.
I'm using the x96Mate which has same soc h616 as tanix tx6s. I'm using boot.img from tx6s without issue, rooted with magisk.

I have followed your instruction and the kernel was built without err, but I don't know how to use it. According to some tuts/guides, I think there should be zImage, boot.img...etc, but there's not. 😄😄😄 

I tried to boot with `Image-5.10.4-stb-616+` for testing => fastboot boot Image-5.10.4-stb-616+.img, but nothing happened (status of fastboot is [OKAY] but nothing). Maybe it needs more steps like adding ramdisk? please guide me.

This is the first time I build kernel 😄, my aim is running docker on android. 😃 thanks!!

**Comment by hexdump0815** [comment]
hello,

for me it sounds that you are trying to run this kernel on android - right? this will most probably not work as it is intended to be used with some regular linux like debian or ubuntu. also this is all very early work in progress, so many things are not working yet ... but things will get forward step by step.

best wishes - hexdump

**Comment by tm4dev** [comment]
yeah now I know it, thanks 😄 
I can see that you have tx6s box, is it locked bootloader? can you compile its android kernel then boot it normally?

I have found my tv box os was built from aosp, I got the source, pulled config.gz from /proc (not modified anything), built it successfully, made a boot.img. But the result is same as above 😢 "fastboot boot boot.img" does nothing. I tried flash img to boot partition but bootloop. well, I think I have made some mistakes, maybe wrong kernel source, not aosp? or maybe the bootloader is locked (but OEM unlock was turned on in Developer options, and with a few checks, it seems like not locked - not sure). Could you give me some advice? Thanks!!

**Comment by hexdump0815** [comment]
sorry - i can't help you with android
