### ISSUE TITLE
DTB compilation fails

### ISSUE THREAD

**Issue by FerGT50** [hexdump0815/linux-mainline-and-mali-allwinner-h3-h6-kernel#2]
Hello, "XFer012" from Armbian forum.

Tried following your notes, but when I issue "make dtbs" I have this error:

`DTC     arch/arm64/boot/dts/allwinner/sun50i-h616-tx6s.dtb
arch/arm64/boot/dts/allwinner/sun50i-h616.dtsi:557.27-574.5: ERROR (phandle_references): /soc/ethernet@5030000: Reference to non-existent node or label "rmii_pins"

  also defined at arch/arm64/boot/dts/allwinner/sun50i-h616-tx6s.dts:99.8-108.3
ERROR: Input tree has errors, aborting (use -f to force output)
scripts/Makefile.lib:328: recipe for target 'arch/arm64/boot/dts/allwinner/sun50i-h616-tx6s.dtb' failed
make[2]: *** [arch/arm64/boot/dts/allwinner/sun50i-h616-tx6s.dtb] Error 2
scripts/Makefile.build:496: recipe for target 'arch/arm64/boot/dts/allwinner' failed
make[1]: *** [arch/arm64/boot/dts/allwinner] Error 2
Makefile:1342: recipe for target 'dtbs' failed
make: *** [dtbs] Error 2`

I followed all the steps, including applying ac200 patch etc.
Started from clean "h616-hdmi" branch from jernej kernel.

Any hint? Thank you very much!

**Comment by hexdump0815** [comment]
hi,

this is strange: rmii_pins should be defined in sun50i-h616.dtsi after this patch is applied: https://github.com/hexdump0815/linux-mainline-and-mali-allwinner-h6-kernel/blob/master/misc.616/patches/ac200-eth-add-to-h616.patch which i guess you did ... i'll have to try to reproduce the problem and will report back if i was able to ...

best wishes - hexdump

ps: maybe you can try to change it into something like this - https://github.com/hexdump0815/linux-mainline-and-mali-allwinner-h6-kernel/commit/2d52361b07622e778f5c903889674826c9e80841#diff-28bc1fc37643501861f931c0088e5f232bf33087a70237cea0b8042345cf7aefL207

update: link to the line did not work - so to change it to "rmii_pins: rmii-pins {" in the h616 dtsi

**Comment by hexdump0815** [comment]
wait - if you only want to use the kernel on the opi zero 2, then i think you can even skip the ac200 patch and tar (on tv boxes ethernet is using the other controller and this is to enable it) and can also remove the tx6s and x96q dts and remove them from the dtb Makefile, but you can also leave all this in as it should not harm ...

**Comment by FerGT50** [comment]
Changing "ext_rmii_pins" in "rmii_pins" in "arch/arm64/boot/dts/allwinner/sun50i-h616.dtsi" (around line 227) did the trick, thanks! 👍 
Now I'm studying the second part of your notes. Thanks for your support!

**Comment by hexdump0815** [comment]
thanks for the feedback - looks like i have to add that to my patches ... before i used my own h616 dtsi and overwrote the one from the git tree - looks like i missed to patch the original one now ... good luck!
