### ISSUE TITLE
Precompiled kernel fails to boot

### ISSUE THREAD

**Issue by FerGT50** [hexdump0815/linux-mainline-and-mali-allwinner-h3-h6-kernel#4]
Hello, it's me again :D

I follow your suggestion and tried to boot your precompiled kernel (https://github.com/hexdump0815/linux-mainline-and-mali-allwinner-h6-kernel/releases/download/5.11.0-rc1-stb-616%2B/5.11.0-rc1-stb-616+.tar.gz)

Unfortunately, it fails booting from microSD; it then tries to boot from network, which fails as well since I don't have the needed infrastructure.

Any hint about what could be wrong?

The log (copied from serial console):

U-Boot SPL 2021.01-rc5-armbian (Apr 07 2021 - 21:07:34 +0000)
DRAM: 512 MiB
Trying to boot from MMC1
NOTICE:  BL31: v2.4(debug):7eee1da-dirty
NOTICE:  BL31: Built : 21:07:25, Apr  7 2021
NOTICE:  BL31: Detected Allwinner H616 SoC (1823)
NOTICE:  BL31: Found U-Boot DTB at 0x4a084b18, model: OrangePi Zero2
INFO:    ARM GICv2 driver initialized
INFO:    PMIC: Probing AXP305 on I2C
INFO:    PMIC: aldo1 voltage: 3.300V
INFO:    PMIC: aldo2 voltage: 3.300V
INFO:    PMIC: aldo3 voltage: 3.300V
INFO:    PMIC: bldo1 voltage: 1.800V
INFO:    PMIC: dcdcd voltage: 1.500V
INFO:    PMIC: dcdce voltage: 3.300V
INFO:    Changed devicetree to reserve BL31 memory.
INFO:    BL31: Platform setup done
INFO:    BL31: Initializing runtime services
INFO:    BL31: cortex_a53: CPU workaround for 855873 was applied
WARNING: BL31: cortex_a53: CPU workaround for 1530924 was missing!
NOTICE:  PSCI: System suspend is unavailable
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x4a000000
INFO:    SPSR = 0x3c9

U-Boot 2021.01-rc5-armbian (Apr 07 2021 - 21:07:34 +0000) Allwinner Technology

CPU:   Allwinner H616 (SUN50I)
Model: OrangePi Zero2
I2C:   ready
DRAM:  512 MiB
MMC:   mmc@4020000: 0
Loading Environment from FAT... Unable to use mmc 0:1... In:    serial@5000000
Out:   serial@5000000
Err:   serial@5000000
Net:   phy interface7
eth0: ethernet@5020000
starting USB...
No working controllers found
Autoboot in 1 seconds, press <Space> to stop
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot/boot.scr
3202 bytes read in 2 ms (1.5 MiB/s)
## Executing script at 4fc00000
U-boot loaded from SD
Boot script loaded from mmc
205 bytes read in 1 ms (200.2 KiB/s)
Failed to load '/boot/dtb/allwinner/sun50i-h616-orangepi-zero2.dtb'
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
No FDT memory address configured. Please configure
the FDT address via "fdt addr <address>" command.
Aborting!
Failed to load '/boot/dtb/allwinner/overlay/sun50i-h6-fixup.scr'
11249450 bytes read in 931 ms (11.5 MiB/s)
32332288 bytes read in 2670 ms (11.5 MiB/s)
Moving Image from 0x40080000 to 0x40200000, end=42160000
## Loading init Ramdisk from Legacy Image at 4fe00000 ...
   Image Name:   uInitrd
   Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
   Data Size:    11249386 Bytes = 10.7 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
SCRIPT FAILED: continuing...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Scanning disk mmc@4020000.blk...
Found 2 disks
No EFI system partition
BootOrder not defined
EFI boot manager: Cannot load any image
starting USB...
No working controllers found
USB is stopped. Please issue 'usb start' first.
starting USB...
No working controllers found
BOOTP broadcast 1
BOOTP broadcast 2
BOOTP broadcast 3
BOOTP broadcast 4
DHCP client bound to address 192.168.1.216 (3271 ms)
*** Warning: no boot file name; using 'C0A801D8.img'

**Comment by hexdump0815** [comment]
u-boot sees the mmc, but cannot find the dtb: "Failed to load '/boot/dtb/allwinner/sun50i-h616-orangepi-zero2.dtb'" - this is why it will not continue to boot i guess ... maybe check the filesystem if the dtb is really there ...

**Comment by FerGT50** [comment]
Good catch. 
I just decompressed your .tar.gz; looks like you packed /boot/dtb/sun50i-h616-orangepi-zero2.dtb etc., without the "allwinner" intermediate folder.
I moved the DTBs and now it boots OK on Armbian unstable, thanks for your support!
